version: "3"
services:
#  jira:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "20012:8080"
#    depends_on:
#      - mysql
#    environment:
#      - TZ=Asia/Shanghai
  mysql:
    image: mysql:5.7
    volumes:
#      - mysql:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=jira
      - MYSQL_USER=jira
      - MYSQL_PASSWORD=zzk93615
      - MYSQL_ROOT_PASSWORD=zzk93615
      - TZ=Asia/Shanghai
#volumes:
#  mysql: {}